base_model: /mnt/image-edit/datasets/duanyufa/FLUX.2-klein-base-4B
output_dir: /mnt/image-edit/datasets/duanyufa/outputs/flux2_klein_base_4b_full_finetune

dataset_type: metadata_tar
metadata_path: /mnt/zixuan_workspace/caption_scripts/vllm_caption_gemma/caption_splits/all_id_1person_caption_end_analysis/sample_250k.jsonl
image_root: ""
image_column: image
caption_column: caption
tar_column: tar_file
tar_cache_size: 8
dummy_length: 8
height: null
width: null
max_pixels: 1048576
num_workers: 0

mixed_precision: bf16
train_batch_size: 1
gradient_accumulation_steps: 4
use_gradient_checkpointing: true
learning_rate: 1.0e-5
lr_scheduler: constant
lr_warmup_steps: 0
min_lr_ratio: 0.1
weight_decay: 0.01
max_grad_norm: 1.0
max_steps: 7813

checkpointing_steps: 500
resume_from_checkpoint: null
log_every: 1
seed: 42
